# Generated by Django 2.2.4 on 2020-08-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(default='player', max_length=1000)),
                ('team', models.CharField(default='team', max_length=1000)),
                ('position', models.CharField(default='position', max_length=1000)),
                ('projection', models.CharField(default='projection', max_length=1000)),
                ('salary', models.CharField(default='salary', max_length=1000)),
                ('std', models.CharField(default='std', max_length=1000)),
            ],
        ),
    ]
