# Generated by Django 3.1 on 2020-08-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lineup'),
    ]

    operations = [
        migrations.CreateModel(
            name='SilverLineup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(default='player', max_length=1000)),
                ('team', models.CharField(default='team', max_length=1000)),
                ('position', models.CharField(default='position', max_length=1000)),
                ('projection', models.CharField(default='projection', max_length=1000)),
                ('salary', models.CharField(default='salary', max_length=1000)),
                ('std', models.CharField(default='std', max_length=1000)),
            ],
        ),
        migrations.RenameModel(
            old_name='Lineup',
            new_name='PlatinumLineup',
        ),
    ]
